docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Intro: intro.md
    - Reference:
        - "Installation and Requirements": install.md
        - Usage: usage.md
        - Middleware: middleware.md
        - "Error Handlers": error-handlers.md
        - "Creating Middleware in Version 1 and 2": creating-middleware.md
        - "Creating Middleware in Version 3": creating-middleware-v3.md
        - "Executing and composing middleware": executing-middleware.md
        - "API Reference": api.md
        - Migration:
          - "To Version 2": migration/to-v2.md
          - "From v2 to v3": migration/to-v3.md
    - v1:
        - "Installation and Requirements": v1/install.md
        - Usage: v1/usage.md
        - Middleware: v1/middleware.md
        - "Error Handlers": v1/error-handlers.md
        - "Creating Middleware": v1/creating-middleware.md
        - "Executing and composing middleware": v1/executing-middleware.md
        - "API Reference": v1/api.md
site_name: zend-stratigility
site_description: zend-stratigility
repo_url: 'https://github.com/zendframework/zend-stratigility'
copyright: 'Copyright (c) 2016-2017 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
